# Generated by Django 4.0.3 on 2022-04-11 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Allergy_drink',
            new_name='DrinkAllergy',
        ),
        migrations.RenameModel(
            old_name='Image',
            new_name='DrinkImage',
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='one_serving_kca',
        ),
        migrations.RemoveField(
            model_name='size',
            name='size_mi',
        ),
        migrations.AddField(
            model_name='drink',
            name='allergies',
            field=models.ManyToManyField(through='products.DrinkAllergy', to='products.allergy'),
        ),
        migrations.AddField(
            model_name='nutrition',
            name='one_serving_kcal',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='size',
            name='size_ml',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='caffein_mg',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='protein_g',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='saturated_fat_g',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='sudium_mg',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='sugar_g',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_fluid_ounce',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterModelTable(
            name='drinkallergy',
            table='drinks_allergies',
        ),
        migrations.AlterModelTable(
            name='drinkimage',
            table='drink_images',
        ),
    ]
